# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NAAMII (नामी)
email: naamiinepal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  &copy NAAMII (नामी)
baseurl: "/naamii" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: we_dont_have_twitter_yet
github_username:  naamiiNepal

# Build settings
markdown: kramdown

# Make "blog" appear in the links of html files inside the blog directory
permalink: /blog/:year/:month/:day/:title

# Exclude some files from build
exclude: [Rakefile]

# Sass minification: No whitespace in generated css
sass:
  style: compressed

# Code highlighter
highlighter: pygments

# Jekyll-scholar configuration
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: all_publications.bib
  bibliography_template: bibtemplate
  repository: ./papers

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"